security:
  firewalls:
    main:
      anonymous: ~
      form_login:
        login_path: login
        check_path: login
    login_firewall:
            pattern:   ^/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
access_control:
  - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
  - { path: ^/, roles: ROLE_ADMIN }